---
- hosts: local
  connection: local
  remote_user: "vagrant"
  become: yes
  vars:
    user: "vagrant"
    app_name: "r3"
    process_name: "binaryapp"
    controllers: "cpu,memory"
    cgroup: "tkpdlimit"
  roles:
    - cgroup